words = [
    "CXX",
    "DCMAKE",
    "DSP",
    "EOF",
    "Werror",
    "bugprone",
    "cmake",
    "conanfile",
    "cppcoreguidelines",
    "cppstd",
    "ctest",
    "direnv",
    "envrc",
    "graphml",
    "gtest",
    "hicpp",
    "libcxx",
    "lifecycle",
    "multigraph",
    "multigraphs",
    "nixbuild",
    "nixpkgs",
    "pkgs",
]
ignore_paths = ["flake.lock"]
